[package]
name = "netcore-grpc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
prost = "0.14"
tonic = "0.14"
tonic-prost = "0.14"
tokio = { version = "1", features = ["rt", "macros", "sync", "time", "net"] }
tokio-stream = { version = "0.1", features = ["net"] }

[build-dependencies]
tonic-prost-build = "0.14"
protoc-bin-vendored = "3"
