#ifndef NETCORE_FFI_H
#define NETCORE_FFI_H

/* generated by cbindgen from core-rs/core-ffi, do not edit */

#include <stdint.h>
#include <stddef.h>

#define MAX_FLOWS_PER_BATCH 20000

#define ANOMALY_COOLDOWN_US 15000000

#define NC_ABI_VERSION 1

#define NC_ADDR_LEN 16

#define NC_RULE_ID_LEN 64

#define NC_MESSAGE_LEN 192

#define NC_DEVICE_NAME_LEN 256

#define NC_FAMILY_IPV4 4

#define NC_FAMILY_IPV6 6

enum NcStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  NC_STATUS_OK = 0,
  NC_STATUS_NULL_ARG = -1,
  NC_STATUS_INVALID_ARG = -2,
  NC_STATUS_STATE = -3,
  NC_STATUS_IO = -4,
  NC_STATUS_CAPTURE = -5,
  NC_STATUS_NO_LIBRARY = -6,
  NC_STATUS_PERMISSION = -7,
  NC_STATUS_PANIC = -8,
  NC_STATUS_RULES = -9,
  NC_STATUS_FORMAT = -10,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum NcStatus NcStatus;
#else
typedef int32_t NcStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum NcAlertSource
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  NC_ALERT_SOURCE_RULE = 0,
  NC_ALERT_SOURCE_ANOMALY = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum NcAlertSource NcAlertSource;
#else
typedef uint32_t NcAlertSource;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum NcSeverity
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  NC_SEVERITY_LOW = 1,
  NC_SEVERITY_MEDIUM = 2,
  NC_SEVERITY_HIGH = 3,
  NC_SEVERITY_CRITICAL = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum NcSeverity NcSeverity;
#else
typedef uint32_t NcSeverity;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum NcCaptureState
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  NC_CAPTURE_STATE_IDLE = 0,
  NC_CAPTURE_STATE_RUNNING = 1,
  NC_CAPTURE_STATE_FINISHED = 2,
  NC_CAPTURE_STATE_FAILED = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum NcCaptureState NcCaptureState;
#else
typedef uint32_t NcCaptureState;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum NcScenario
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  NC_SCENARIO_MIXED = 0,
  NC_SCENARIO_PORT_SCAN = 1,
  NC_SCENARIO_DNS_TUNNEL = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum NcScenario NcScenario;
#else
typedef uint32_t NcScenario;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum NcAnalyticsState
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  NC_ANALYTICS_STATE_OFF = 0,
  NC_ANALYTICS_STATE_CONNECTING = 1,
  NC_ANALYTICS_STATE_CONNECTED = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum NcAnalyticsState NcAnalyticsState;
#else
typedef uint32_t NcAnalyticsState;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

typedef struct NcCore NcCore;

typedef struct NcConfig {
  uint32_t max_flows;
  uint32_t flow_idle_timeout_ms;
  uint32_t top_n;
  uint32_t snaplen;
  uint32_t link_type;
} NcConfig;

typedef struct NcStats {
  uint64_t packets;
  uint64_t bytes;
  uint64_t ipv4;
  uint64_t ipv6;
  uint64_t tcp;
  uint64_t udp;
  uint64_t icmp;
  uint64_t other_l4;
  uint64_t non_ip;
  uint64_t fragments;
  uint64_t dns;
  uint64_t dns_errors;
  uint64_t parse_errors;
  uint64_t active_flows;
  uint64_t evicted_flows;
  uint64_t expired_flows;
  uint64_t last_ts_us;
  uint64_t capture_dropped;
  uint64_t alerts_total;
  uint64_t alerts_dropped;
  uint64_t capture_state;
  uint64_t rules_loaded;
  uint64_t analytics_state;
  uint64_t analytics_sent;
  uint64_t analytics_dropped;
} NcStats;

typedef struct NcFlow {
  uint8_t a_addr[NC_ADDR_LEN];
  uint8_t b_addr[NC_ADDR_LEN];
  uint16_t a_port;
  uint16_t b_port;
  uint8_t proto;
  uint8_t family;
  uint8_t tcp_flags;
  uint8_t reserved;
  uint64_t packets_ab;
  uint64_t packets_ba;
  uint64_t bytes_ab;
  uint64_t bytes_ba;
  uint64_t first_seen_us;
  uint64_t last_seen_us;
} NcFlow;

typedef struct NcAlert {
  uint64_t ts_us;
  double score;
  uint32_t severity;
  uint32_t source;
  uint8_t src_addr[NC_ADDR_LEN];
  uint8_t family;
  uint8_t reserved[7];
  uint8_t rule_id[NC_RULE_ID_LEN];
  uint8_t message[NC_MESSAGE_LEN];
} NcAlert;

typedef struct NcDevice {
  uint8_t name[NC_DEVICE_NAME_LEN];
  uint8_t description[NC_DEVICE_NAME_LEN];
  uint32_t flags;
} NcDevice;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

uint32_t core_abi_version(void);

struct NcCore *core_create(const struct NcConfig *config);

void core_destroy(struct NcCore *core);

int32_t core_feed_packet(struct NcCore *core,
                         uint64_t ts_us,
                         const uint8_t *data,
                         uint32_t caplen,
                         uint32_t wire_len);

int32_t core_open_live(struct NcCore *core, const char *iface, uint8_t promisc);

int32_t core_open_file(struct NcCore *core, const char *path, uint8_t realtime);

int32_t core_load_rules(struct NcCore *core, const char *path);

int32_t core_connect_analytics(struct NcCore *core, const char *endpoint);

int32_t core_disconnect_analytics(struct NcCore *core);

int32_t core_start(struct NcCore *core);

int32_t core_stop(struct NcCore *core);

int32_t core_poll_stats(struct NcCore *core, struct NcStats *out);

int32_t core_poll_top_flows(struct NcCore *core,
                            struct NcFlow *out,
                            uint32_t capacity,
                            uint32_t *written);

int32_t core_poll_alert(struct NcCore *core, struct NcAlert *out);

int32_t core_last_error(const struct NcCore *core, char *buf, uint32_t len);

int32_t core_write_demo_pcap(const char *path, uint32_t scenario, uint32_t packets, uint64_t seed);

int32_t core_list_devices(struct NcDevice *out, uint32_t capacity, uint32_t *total);

const char *core_status_str(int32_t status);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NETCORE_FFI_H */
